### PR TITLE
#5 Fixed typing for the initial state in useState

### PR DESCRIPTION
**Pull request by MrStobbart**
Fixed the types for the initial state from useState hook.
I used the official types from [react](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts). (Line 846)

### CODE REVIEW

**Comment by troch** [comment]
As answered in the issue, typings are generated so your fix will be erased by the next build.

**Comment by troch** [comment]
No idea yet why there is this issue, and how to fix it.

**Comment by troch** [comment]
Got it: `useState` argument has a type signature of `() => S | S` which means "a function returning a type S or returning a type S" rather than "a function returning a type S, or a type S". It should be typed `(() => S) | S`, like you did here. Going to fix it in a PR.

**Comment by troch** [comment]
OK, fixed in 1.0.1, thanks for bringing my attention to the problem

**Comment by MrStobbart** [comment]
No worries and thanks for you good work! I could have had the idea myself that the typing are generated, thanks for the info :)

**Pull request closed without merging**
