### PR TITLE
fix action.type check

### PR DESCRIPTION
**Pull request by cherepanov**
Didn't get what action.type is for, but got exception with useState(null).

### CODE REVIEW

**Comment by troch** [comment]
Hello @cherepanov, thanks for your contribution. Could you remove dist from git please?

**Comment by cherepanov** [comment]
done

**Comment by troch** [comment]
OK, but also add `dist` back to `.gitignore`?

**Comment by cherepanov** [comment]
ops, done

**Comment by troch** [comment]
Hey, sorry for not going back to it. It has been fixed while maintaining the project and setting TS to strict mode.

**Pull request closed without merging**
